import Head from "next/head";
import Image from "next/image";

import NavBar from "../components/Navbar";

const Main = () => {
    return (
        <div>
            <Head>
                <title>Ryan Nograles</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="content">
                <NavBar />
            </main>

            <footer>
                <p>Copyright @ Ryan Nograles</p>
                <p>
                    Powered by{" "}
                    <span>
                        <Image
                            src="/vercel.svg"
                            alt="Vercel Logo"
                            width={72}
                            height={16}
                        />
                    </span>
                </p>
            </footer>
        </div>
    );
};

export default Main;
